-injars build/kGuard-raw.jar
-outjars ../plugins/kGuard-1.0.0.jar

-libraryjars <java.home>/jmods/java.base.jmod(!**.jar;!module-info.class)
-libraryjars <java.home>/jmods/java.net.http.jmod(!**.jar;!module-info.class)
-libraryjars ../velocity.jar

-dontwarn **
-dontskipnonpubliclibraryclasses
-dontoptimize

-overloadaggressively
-repackageclasses 'com.keydal.kguard'

-keepattributes *Annotation*,Signature,InnerClasses,EnclosingMethod

-keep class com.keydal.kguard.KGuardPlugin {
    public <init>(...);
    public void onProxyInit(com.velocitypowered.api.event.proxy.ProxyInitializeEvent);
    public void onProxyShutdown(com.velocitypowered.api.event.proxy.ProxyShutdownEvent);
    public void onHeartbeatFailed(java.lang.String);
}

-keepclassmembers class * {
    @com.velocitypowered.api.event.Subscribe <methods>;
    @com.google.inject.Inject <init>(...);
}

-adaptresourcefilenames **.properties,**.json
-adaptresourcefilecontents velocity-plugin.json
